### ISSUE TITLE
md5sum changed on octeon-roc-v0.2.tar.gz

### ISSUE THREAD

**Issue by mgsmith1000** [MarvellEmbeddedProcessors/marvell-octeon-roc#9]
Prior to 10 June 2024, when I downloaded v0.2 from https://github.com/MarvellEmbeddedProcessors/marvell-vpp/archive/refs/tags/octeon-roc-v0.2.tar.gz, the md5sum of the tarball was a72bb3b27fd3bbaf58aadd99514620e1. Starting on that date, the md5sum of a fresh download of the file changed to 3e122beb30d57d6f70ea5ee106465b3b.

I noticed this because it caused failures of a clean build from the stable/2402 branch of https://github.com/FDio/vpp.
It might not indicate any problem. I could not find any difference between the contents of the old and new files using 'diff -r'. I am just reporting it because it's unusual for the checksum of previously released source archive to change and I thought someone may want to verify that there is no issue.

**Comment by akamaluddin** [comment]
There is a url change for this repo hence the md5sum change. The tarball remains the same.

Recommend moving to stable/2406 where this fix is incorporated and which uses octeon-roc-v0.5. Meanwhile we will push updated md5sum patch for stable/2402 as well. Thanks for reporting the issue.
